import { Phonetic } from '../models/phonetic';

export const PHONETICS: Phonetic[] = [
  {id: 0,  character: 'a', morse: '●— ',    telephony: 'Alpha',    police: 'Adam'},
  {id: 1,  character: 'b', morse: '—●●● ',  telephony: 'Bravo',    police: 'Boy'},
  {id: 2,  character: 'c', morse: '—●—● ',  telephony: 'Charlie',  police: 'Charles'},
  {id: 3,  character: 'd', morse: '—●● ',   telephony: 'Delta',    police: 'David'},
  {id: 4,  character: 'e', morse: '● ',     telephony: 'Echo',     police: 'Edward'},
  {id: 5,  character: 'f', morse: '●●—● ',  telephony: 'Foxtrot',  police: 'Frank'},
  {id: 6,  character: 'g', morse: '——●',   telephony: 'Golf',     police: 'George'},
  {id: 7,  character: 'h', morse: '●●●●',  telephony: 'Hotel',    police: 'Henry'},
  {id: 8,  character: 'i', morse: '●●',    telephony: 'India',    police: 'Ida'},
  {id: 9,  character: 'j', morse: '●———',  telephony: 'Juliett',  police: 'John'},
  {id: 10, character: 'k', morse: '—●—',   telephony: 'Kilo',     police: 'King'},
  {id: 11, character: 'l', morse: '●—●●',  telephony: 'Lima',     police: 'Lincoln'},
  {id: 12, character: 'm', morse: '——',    telephony: 'Mike',     police: 'Mary'},
  {id: 13, character: 'n', morse: '—●',    telephony: 'November', police: 'Nora'},
  {id: 14, character: 'o', morse: '———',   telephony: 'Oscar',    police: 'Ocean'},
  {id: 15, character: 'p', morse: '●——●',  telephony: 'Papa',     police: 'Paul'},
  {id: 16, character: 'q', morse: '——●—',  telephony: 'Quebec',   police: 'Queen'},
  {id: 17, character: 'r', morse: '●—●',   telephony: 'Romeo',    police: 'Robert'},
  {id: 18, character: 's', morse: '●●●',   telephony: 'Sierra',   police: 'Sam'},
  {id: 19, character: 't', morse: '—',     telephony: 'Tango',    police: 'Tom'},
  {id: 20, character: 'u', morse: '●●—',   telephony: 'Uniform',  police: 'Union'},
  {id: 21, character: 'v', morse: '●●●—',  telephony: 'Victor',   police: 'Victor'},
  {id: 22, character: 'w', morse: '●——',   telephony: 'Whiskey',  police: 'William'},
  {id: 23, character: 'x', morse: '—●●—',  telephony: 'X—ray',    police: 'X—ray'},
  {id: 24, character: 'y', morse: '—●——',  telephony: 'Yankee',   police: 'Young/Yellow'},
  {id: 25, character: 'z', morse: '——●●',  telephony: 'Zulu',     police: 'Zebra'},
  {id: 26, character: '1', morse: '●————', telephony: 'One',      police: 'One'},
  {id: 27, character: '2', morse: '●●———', telephony: 'Two',      police: 'Two'},
  {id: 28, character: '3', morse: '●●●——', telephony: 'Three',    police: 'Three'},
  {id: 29, character: '4', morse: '●●●●—', telephony: 'Four',     police: 'Four'},
  {id: 30, character: '5', morse: '●●●●●', telephony: 'Five',     police: 'Five'},
  {id: 31, character: '6', morse: '—●●●●', telephony: 'Six',      police: 'Six'},
  {id: 32, character: '7', morse: '——●●●', telephony: 'Seven',    police: 'Seven'},
  {id: 33, character: '8', morse: '———●●', telephony: 'Eight',    police: 'Eight'},
  {id: 34, character: '9', morse: '————●', telephony: 'Nine',     police: 'Nine'},
  {id: 35, character: '0', morse: '—————', telephony: 'Zero',     police: 'Zero'},
  {id: 36, character: ' ', morse: ' 3 SECOND PAUSE ',   telephony: 'Space',    police: 'Space'}
];

